-- ============================================================================
-- Pattern 05 · Tree / Hierarchy · THE ALTERNATIVE: STORE THE EDGE
-- The canonical form (the logical model) of a BOM is parts plus parent -> child
-- links. This lane stores exactly that, one edge row per link, and derives
-- position by walking the edges instead of storing it in every part:
--
--   RE-PARENT is a SINGLE edge update: the subtree follows, because position
--   was never stored. O(subtree) rewrites become O(1).
--   EXPLODE walks the edges level by level with CONNECT BY (never a recursive
--   CTE, which dams each level into an intermediate relation).
--   WHERE-USED walks upward, by CONNECT BY or a SQL/PGQ GRAPH_TABLE match over
--   the same rows.
--
-- WHY IT LOSES THIS WORKLOAD (measured on 26ai Free, an 88,573-part BOM):
-- the walk is paid on every read. Exploding a 1,092-part assembly took
-- 1,116 us with CONNECT BY (parts joined in) and 1,945 us with GRAPH_TABLE,
-- against 765 us for the path's prefix scan. At 2 million explosions a day
-- that premium outweighs the path's rewrites until a typical move passes about
-- 88,000 parts. Store the edge when moves are that large and that frequent,
-- or when the questions are genuinely graph-shaped (many hops, many parents,
-- ad hoc). For this workload, keep the path and read this lane as the
-- measured alternative.
-- Run:  sqlplus cmp_user/CmpUser2026@localhost:1521/FREEPDB1 @02-converged.sql
-- ============================================================================

BEGIN
  FOR r IN (SELECT table_name FROM user_tables
            WHERE table_name IN ('TR_BOM_EDGES','TR_PARTS')
            ORDER BY table_name) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

CREATE TABLE tr_parts (
  part_id VARCHAR2(12) PRIMARY KEY,
  name    VARCHAR2(60) NOT NULL
);

-- The tree/DAG is EDGES, not baked paths. One row per parent->child link.
CREATE TABLE tr_bom_edges (
  edge_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id VARCHAR2(12) NOT NULL REFERENCES tr_parts(part_id),
  child_id  VARCHAR2(12) NOT NULL REFERENCES tr_parts(part_id),
  qty       NUMBER(10)   DEFAULT 1 NOT NULL
);
CREATE INDEX tr_ix_edge_parent ON tr_bom_edges (parent_id);
CREATE INDEX tr_ix_edge_child  ON tr_bom_edges (child_id);

INSERT INTO tr_parts VALUES ('P-1000','Bicycle');
INSERT INTO tr_parts VALUES ('P-1100','Wheelset');
INSERT INTO tr_parts VALUES ('P-1110','Wheel');
INSERT INTO tr_parts VALUES ('P-1111','Spoke');
INSERT INTO tr_parts VALUES ('P-1200','Frame');
-- P-1300 (Trailer) shares the wheel with the bicycle -- a DAG, not a pure tree.
INSERT INTO tr_parts VALUES ('P-1300','Trailer');
INSERT INTO tr_bom_edges (parent_id,child_id,qty) VALUES ('P-1000','P-1100',1);
INSERT INTO tr_bom_edges (parent_id,child_id,qty) VALUES ('P-1000','P-1200',1);
INSERT INTO tr_bom_edges (parent_id,child_id,qty) VALUES ('P-1100','P-1110',2);
INSERT INTO tr_bom_edges (parent_id,child_id,qty) VALUES ('P-1110','P-1111',32);
INSERT INTO tr_bom_edges (parent_id,child_id,qty) VALUES ('P-1300','P-1110',2);
COMMIT;

CREATE OR REPLACE PROPERTY GRAPH tr_bom_graph
  VERTEX TABLES ( tr_parts KEY (part_id) LABEL part PROPERTIES (part_id, name) )
  EDGE TABLES ( tr_bom_edges KEY (edge_id)
     SOURCE KEY (parent_id) REFERENCES tr_parts (part_id)
     DESTINATION KEY (child_id) REFERENCES tr_parts (part_id)
     LABEL contains PROPERTIES (qty) );

-- READ 1 -- explode the wheelset (all components, any depth): CONNECT BY walks the edges,
-- and each component's name comes from its part row, as the path lane returns it.
-- @step Explode the wheelset with CONNECT BY
-- @measure-read read
-- @note Native recursion walks the edges level by level: one index probe per part, then each part's row for its name, paid on every explosion.
-- @why Read/write is where this lane loses: the walk probes the edge index once per part and joins each part's row, so it costs about 1.5x the path's prefix scan on every explosion (measured on 26ai: 1,116 us against 765 us for a 1,092-part assembly), two million times a day.
-- @look The wheel and the spoke with their names, the same answer as the path lane's prefix scan.
-- @figure erd.svg Part, BOM edge and change order in canonical form, beside the fan-out of one re-parent across materialized paths
-- @mongo db.aggregate([{ $sql: `
-- @mongo   SELECT h.child_id AS part, p.name, h.qty, h.depth
-- @mongo   FROM  (SELECT child_id, qty, LEVEL AS depth
-- @mongo          FROM   tr_bom_edges
-- @mongo          START WITH parent_id = 'P-1100'
-- @mongo          CONNECT BY PRIOR child_id = parent_id) h
-- @mongo   JOIN   tr_parts p ON p.part_id = h.child_id
-- @mongo   ORDER  BY part
-- @mongo ` }])
SELECT h.child_id AS part, p.name, h.qty, h.depth
FROM  (SELECT child_id, qty, LEVEL AS depth
       FROM   tr_bom_edges
       START WITH parent_id = 'P-1100'
       CONNECT BY PRIOR child_id = parent_id) h
JOIN   tr_parts p ON p.part_id = h.child_id
ORDER  BY part;

-- READ 2 -- where-used: which assemblies contain the wheel? Walked upward with a
-- SQL/PGQ graph match over the same rows (the path lane reads it from one document).
-- @step Walk upward with a graph match: where is the wheel used?
-- @note Multi-parent, N-hop, upward traversal over the edge rows: no second structure, but a walk on every question.
-- @why Diversity: where-used runs upward across shared parts. A SQL/PGQ graph over the same two tables answers it with nothing extra to maintain, but it walks to find what the path lane stores: measured, a GRAPH_TABLE where-used costs about 7x a CONNECT BY walk, and 1.6 to 10x the path on explosions. Graph matching pays off for genuinely graph-shaped questions, not for a fixed hierarchy.
-- @look P-1300, the trailer that shares the wheel, appears alongside the bicycle's assemblies.
-- @mongo db.aggregate([{ $sql: `
-- @mongo   SELECT assembly
-- @mongo   FROM   GRAPH_TABLE (tr_bom_graph
-- @mongo            MATCH (a IS part)-[IS contains]->{1,4}(p IS part)
-- @mongo            WHERE p.part_id = 'P-1110'
-- @mongo            COLUMNS (a.part_id AS assembly))
-- @mongo ` }])
SELECT assembly
FROM   GRAPH_TABLE (tr_bom_graph
         MATCH (a IS part)-[IS contains]->{1,4}(p IS part)
         WHERE p.part_id = 'P-1110'
         COLUMNS (a.part_id AS assembly));
-- ^ returns P-1100, P-1000, AND P-1300 (the trailer that shares the wheel).

-- THE EDGE'S STRENGTH -- re-parent the wheelset under the frame: ONE row.
-- The entire subtree moves with it; no descendant paths to rewrite.
-- @step Re-parent the wheelset under the frame
-- @note One edge update: the entire subtree moves with it, no descendant paths to rewrite.
-- @why Update locality is the edge's strength: position is derived, so the move is one edge row however many parts hang beneath it. It is the cheaper write by far, but writes are 200 a day here and reads 2 million; the saving only outweighs the read premium once a typical move passes about 88,000 parts.
-- @look Rows affected is 1; Measure it shows redo near 1 KB for a subtree of any size.
-- @measure reparent
-- @mongo db.aggregate([{ $sql: `
-- @mongo   UPDATE tr_bom_edges SET parent_id = 'P-1200'
-- @mongo   WHERE  parent_id = 'P-1000' AND child_id = 'P-1100'
-- @mongo ` }])
UPDATE tr_bom_edges SET parent_id = 'P-1200'
WHERE  parent_id = 'P-1000' AND child_id = 'P-1100';
COMMIT;

-- Re-explode: the wheelset (and everything under it) now hangs off the frame,
-- from that single edge change.
-- @step Re-explode: confirm the subtree moved with the edge
-- @note The wheelset (and everything under it) now hangs off the frame, from that single edge change.
-- @why Update locality, resolved: the next explosion walks the edges as they are now, so the whole subtree moved with that one row.
-- @look P-1100 and its children now appear under P-1200.
-- @mongo db.aggregate([{ $sql: `
-- @mongo   SELECT LPAD(' ', 2*(LEVEL-1)) || child_id AS component, LEVEL AS depth
-- @mongo   FROM   tr_bom_edges
-- @mongo   START WITH parent_id = 'P-1000'
-- @mongo   CONNECT BY PRIOR child_id = parent_id
-- @mongo   ORDER SIBLINGS BY child_id
-- @mongo ` }])
SELECT LPAD(' ', 2*(LEVEL-1)) || child_id AS component, LEVEL AS depth
FROM   tr_bom_edges
START WITH parent_id = 'P-1000'
CONNECT BY PRIOR child_id = parent_id
ORDER SIBLINGS BY child_id;
