-- ============================================================================
-- Pattern 05 · Tree / Hierarchy · THE CONVERGED ALTERNATIVE
-- Split the two questions the materialized path was trying to answer at once.
--
--   TREE structure lives in ADJACENCY EDGES (parent_id -> child_id). Re-parenting
--   is a SINGLE edge update -- the subtree follows automatically because position
--   is not baked into every node. Write amplification for a reorg drops from
--   O(subtree) to O(1).
--
--   SUBTREE / EXPLOSION reads use native recursion -- CONNECT BY streams the
--   frontier in one pass (emit CONNECT BY or GRAPH_TABLE for hierarchy, never a
--   recursive CTE, which dams each level into an intermediate relation the CBO
--   can barely optimize).
--
--   GENUINE GRAPH questions -- "which assemblies use this wheel?", multi-parent,
--   N hops, the DAG a downward prefix string cannot express -- use SQL/PGQ
--   GRAPH_TABLE over the SAME rows. No separate graph database to sync.
--
-- The needle-flip, resolved: the write that the path made expensive (reorg)
-- becomes one row, and the read the path could not do at all (where-used across
-- shared components) becomes one graph match.
-- Run:  sqlplus cmp_user/CmpUser2026@localhost:1521/FREEPDB1 @02-converged.sql
-- ============================================================================

BEGIN
  FOR r IN (SELECT table_name FROM user_tables
            WHERE table_name IN ('TR_BOM_EDGES','TR_PARTS')
            ORDER BY table_name) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

CREATE TABLE tr_parts (
  part_id VARCHAR2(12) PRIMARY KEY,
  name    VARCHAR2(60) NOT NULL
);

-- The tree/DAG is EDGES, not baked paths. One row per parent->child link.
CREATE TABLE tr_bom_edges (
  edge_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id VARCHAR2(12) NOT NULL REFERENCES tr_parts(part_id),
  child_id  VARCHAR2(12) NOT NULL REFERENCES tr_parts(part_id),
  qty       NUMBER(10)   DEFAULT 1 NOT NULL
);
CREATE INDEX tr_ix_edge_parent ON tr_bom_edges (parent_id);
CREATE INDEX tr_ix_edge_child  ON tr_bom_edges (child_id);

INSERT INTO tr_parts VALUES ('P-1000','Bicycle');
INSERT INTO tr_parts VALUES ('P-1100','Wheelset');
INSERT INTO tr_parts VALUES ('P-1110','Wheel');
INSERT INTO tr_parts VALUES ('P-1111','Spoke');
INSERT INTO tr_parts VALUES ('P-1200','Frame');
-- P-1300 (Trailer) shares the wheel with the bicycle -- a DAG, not a pure tree.
INSERT INTO tr_parts VALUES ('P-1300','Trailer');
INSERT INTO tr_bom_edges (parent_id,child_id,qty) VALUES ('P-1000','P-1100',1);
INSERT INTO tr_bom_edges (parent_id,child_id,qty) VALUES ('P-1000','P-1200',1);
INSERT INTO tr_bom_edges (parent_id,child_id,qty) VALUES ('P-1100','P-1110',2);
INSERT INTO tr_bom_edges (parent_id,child_id,qty) VALUES ('P-1110','P-1111',32);
INSERT INTO tr_bom_edges (parent_id,child_id,qty) VALUES ('P-1300','P-1110',2);
COMMIT;

CREATE OR REPLACE PROPERTY GRAPH tr_bom_graph
  VERTEX TABLES ( tr_parts KEY (part_id) LABEL part PROPERTIES (part_id, name) )
  EDGE TABLES ( tr_bom_edges KEY (edge_id)
     SOURCE KEY (parent_id) REFERENCES tr_parts (part_id)
     DESTINATION KEY (child_id) REFERENCES tr_parts (part_id)
     LABEL contains PROPERTIES (qty) );

-- READ 1 -- explode the bicycle (all components, any depth): CONNECT BY, one pass.
SELECT LPAD(' ', 2*(LEVEL-1)) || child_id AS component, qty, LEVEL AS depth
FROM   tr_bom_edges
START WITH parent_id = 'P-1000'
CONNECT BY PRIOR child_id = parent_id
ORDER SIBLINGS BY child_id;

-- READ 2 -- where-used: which assemblies contain the wheel? The multi-parent,
-- N-hop question the materialized path could not express. SQL/PGQ, same rows.
SELECT assembly
FROM   GRAPH_TABLE (tr_bom_graph
         MATCH (a IS part)-[IS contains]->{1,4}(p IS part)
         WHERE p.part_id = 'P-1110'
         COLUMNS (a.part_id AS assembly));
-- ^ returns P-1100, P-1000, AND P-1300 (the trailer that shares the wheel).

-- THE NEEDLE-FLIP, RESOLVED -- re-parent the wheelset under the frame: ONE row.
-- The entire subtree moves with it; no descendant paths to rewrite.
UPDATE tr_bom_edges SET parent_id = 'P-1200'
WHERE  parent_id = 'P-1000' AND child_id = 'P-1100';
COMMIT;

-- Re-explode: the wheelset (and everything under it) now hangs off the frame,
-- from that single edge change.
SELECT LPAD(' ', 2*(LEVEL-1)) || child_id AS component, LEVEL AS depth
FROM   tr_bom_edges
START WITH parent_id = 'P-1000'
CONNECT BY PRIOR child_id = parent_id
ORDER SIBLINGS BY child_id;
