-- ============================================================================
-- Pattern 02 · Computed · THE CONVERGED ALTERNATIVE
-- Two moves, both keeping the read win without paying whole-document write amp.
--
-- 1) CDRs are APPEND-ONLY relational rows — one small insert per CDR, no parent
--    rewrite, no hot-document contention. A maintained summary carries the
--    rollup and is kept current IN THE SAME TRANSACTION by a row trigger:
--    "Computed, with a staleness window of zero." (Declarative equivalent:
--    a materialized view WITH REFRESH FAST ON COMMIT over a CDR mview log.)
--
-- 2) Hot Top-N becomes an INDEX RANGE SCAN. A descending index on the summary's
--    usage column turns "top talkers" into an O(log n) seek + FETCH FIRST N —
--    no SUM, no SORT, no full-collection scan. This is the field pattern behind
--    the 60s -> 500ms dashboard result (a real landing page, anonymized).
--
-- The needle-flip, resolved: the read stays cheap; the write drops from a full
-- document rewrite to a single-row counter update; the ranking stops being a
-- scan. The CBO plans all of it, ACID, one transaction.
-- Run:  sqlplus cmp_user/CmpUser2026@localhost:1521/FREEPDB1 @02-converged.sql
-- ============================================================================

BEGIN
  FOR r IN (SELECT table_name FROM user_tables
            WHERE table_name IN ('CP_CDR','CP_SUBSCRIBER_USAGE','CP_SUBSCRIBERS')
            ORDER BY table_name) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

CREATE TABLE cp_subscribers (
  subscriber_id VARCHAR2(12)  PRIMARY KEY,
  msisdn        VARCHAR2(24)  NOT NULL,
  plan          VARCHAR2(16)  NOT NULL
);

-- Append-only fact: one small row per CDR. No document to rewrite.
CREATE TABLE cp_cdr (
  cdr_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscriber_id VARCHAR2(12) NOT NULL REFERENCES cp_subscribers(subscriber_id),
  mb            NUMBER(12,2) DEFAULT 0 NOT NULL,
  minutes       NUMBER(10)   DEFAULT 0 NOT NULL,
  cost          NUMBER(12,4) DEFAULT 0 NOT NULL,
  cdr_ts        TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL
);

-- Maintained rollup: "Computed with staleness = 0."
CREATE TABLE cp_subscriber_usage (
  subscriber_id VARCHAR2(12) PRIMARY KEY REFERENCES cp_subscribers(subscriber_id),
  total_mb      NUMBER(14,2) DEFAULT 0 NOT NULL,
  total_min     NUMBER(12)   DEFAULT 0 NOT NULL,
  cost          NUMBER(14,4) DEFAULT 0 NOT NULL
);

-- The descending index that turns Top-N into a range scan (not a sort).
CREATE INDEX cp_ix_usage_topn ON cp_subscriber_usage (total_mb DESC, subscriber_id);

CREATE OR REPLACE TRIGGER cp_trg_usage
AFTER INSERT ON cp_cdr
FOR EACH ROW
BEGIN
  MERGE INTO cp_subscriber_usage u
  USING (SELECT :NEW.subscriber_id AS sid FROM dual) s
  ON (u.subscriber_id = s.sid)
  WHEN MATCHED THEN UPDATE SET
    u.total_mb  = u.total_mb  + :NEW.mb,
    u.total_min = u.total_min + :NEW.minutes,
    u.cost      = u.cost      + :NEW.cost
  WHEN NOT MATCHED THEN INSERT (subscriber_id, total_mb, total_min, cost)
    VALUES (:NEW.subscriber_id, :NEW.mb, :NEW.minutes, :NEW.cost);
END;
/

INSERT INTO cp_subscribers VALUES ('S-001','+1-202-555-0111','UNLIMITED');
INSERT INTO cp_subscribers VALUES ('S-002','+1-202-555-0122','METERED');
INSERT INTO cp_subscribers VALUES ('S-003','+1-202-555-0133','UNLIMITED');

-- CDRs stream in as tiny appends; the summary tracks them in the same commit.
INSERT INTO cp_cdr (subscriber_id, mb, minutes, cost) VALUES ('S-001',120,12,0.36);
INSERT INTO cp_cdr (subscriber_id, mb, minutes, cost) VALUES ('S-001',300,20,0.90);
INSERT INTO cp_cdr (subscriber_id, mb, minutes, cost) VALUES ('S-002', 50, 5,0.15);
INSERT INTO cp_cdr (subscriber_id, mb, minutes, cost) VALUES ('S-003',900,40,2.70);
COMMIT;

-- Account page read: the rollup is already there (staleness = 0), one PK lookup.
SELECT subscriber_id, total_mb, cost FROM cp_subscriber_usage WHERE subscriber_id = 'S-001';

-- Hot Top-N: an index range scan on cp_ix_usage_topn + FETCH FIRST N.
-- (EXPLAIN PLAN FOR this SELECT shows INDEX RANGE SCAN, not SORT ORDER BY.)
SELECT subscriber_id, total_mb, cost
FROM   cp_subscriber_usage
ORDER  BY total_mb DESC
FETCH  FIRST 5 ROWS ONLY;

-- Prefer the document shape at the API? Project it — rollup included, live.
CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW cp_subscriber_dv AS
SELECT JSON {
  '_id'    : s.subscriber_id,
  'msisdn' : s.msisdn WITH UPDATE,
  'plan'   : s.plan   WITH UPDATE,
  'cycleUsage' : ( SELECT JSON { 'totalMB' : u.total_mb,
                                 'totalMin': u.total_min,
                                 'cost'    : u.cost }
                   FROM cp_subscriber_usage u WITH NOUPDATE
                   WHERE u.subscriber_id = s.subscriber_id )
} FROM cp_subscribers s WITH INSERT UPDATE DELETE;

SELECT JSON_SERIALIZE(data PRETTY) AS subscriber_document
FROM   cp_subscriber_dv WHERE JSON_VALUE(data,'$._id') = 'S-001';
