-- ============================================================================
-- Pattern 02 · Computed · THE CONVERGED ALTERNATIVE
-- Same facts, same precomputed summary; the summary just lives in a narrow row.
--
-- 1) CDRs are APPEND-ONLY relational rows: one small insert per CDR (the same
--    half of the write the document design pays). A maintained summary row
--    carries the cycle totals and is kept current IN THE SAME TRANSACTION by a
--    row trigger: "Computed, with a staleness window of zero." (Declarative
--    equivalent: a materialized view WITH REFRESH FAST ON COMMIT over a CDR log;
--    exact, but measured on 26ai at ~8x the trigger's redo and ~40x its time per
--    single-row commit. Pattern 03 has the breakdown.)
--    The subscriber's profile lives in cp_subscribers and is never touched by a CDR.
--
-- 2) Hot Top-N becomes an INDEX RANGE SCAN. A descending index on the summary's
--    usage column turns "top talkers" into an O(log n) seek + FETCH FIRST N,
--    no SORT, no full-collection scan. This is the field pattern behind the
--    60s -> 500ms dashboard result (a real landing page, anonymized).
--
-- The needle-flip, resolved: the summary update stops rewriting the subscriber.
-- Measured on 26ai Free, the summary row update logs ~1.0 KB of redo; the same
-- three counters inside a ~3.5 KB subscriber document log ~8.3 KB. The CDR write
-- stays flat however large the profile is. Rate checks read the narrow row by
-- primary key (4.0 us against 9.5 us to pull a counter from a ~3.4 KB document);
-- only the account page joins it through the duality view (about 30% more read
-- work), a couple of times a day. The CBO plans all of it, ACID, one transaction.
--
-- When to flip back: a rollup-only document (the counters alone, the profile
-- elsewhere) measured within 1.5x of the summary row; a closed cycle's final bill
-- can live on a document. The 8 KB block is not a floor: redo and undo grow with
-- the bytes rewritten, so the summary inside the full profile loses on every CDR.
-- Run:  sqlplus cmp_user/CmpUser2026@localhost:1521/FREEPDB1 @02-converged.sql
-- ============================================================================

BEGIN
  FOR r IN (SELECT table_name FROM user_tables
            WHERE table_name IN ('CP_CDR','CP_SUBSCRIBER_USAGE','CP_SUBSCRIBERS')
            ORDER BY table_name) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

CREATE TABLE cp_subscribers (
  subscriber_id VARCHAR2(12)  PRIMARY KEY,
  msisdn        VARCHAR2(24)  NOT NULL,
  plan          VARCHAR2(16)  NOT NULL,
  profile       JSON          NOT NULL   -- the same ~6 KB profile the document carries; CDRs never touch it
);

-- Append-only fact: one small row per CDR. No document to rewrite.
CREATE TABLE cp_cdr (
  cdr_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscriber_id VARCHAR2(12) NOT NULL REFERENCES cp_subscribers(subscriber_id),
  mb            NUMBER(12,2) DEFAULT 0 NOT NULL,
  minutes       NUMBER(10)   DEFAULT 0 NOT NULL,
  cost          NUMBER(12,4) DEFAULT 0 NOT NULL,
  cdr_ts        TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL
);

-- Maintained rollup: "Computed with staleness = 0."
CREATE TABLE cp_subscriber_usage (
  subscriber_id VARCHAR2(12) PRIMARY KEY REFERENCES cp_subscribers(subscriber_id),
  total_mb      NUMBER(14,2) DEFAULT 0 NOT NULL,
  total_min     NUMBER(12)   DEFAULT 0 NOT NULL,
  cost          NUMBER(14,4) DEFAULT 0 NOT NULL
);

-- The descending index that turns Top-N into a range scan (not a sort).
CREATE INDEX cp_ix_usage_topn ON cp_subscriber_usage (total_mb DESC, subscriber_id);

CREATE OR REPLACE TRIGGER cp_trg_usage
AFTER INSERT ON cp_cdr
FOR EACH ROW
BEGIN
  MERGE INTO cp_subscriber_usage u
  USING (SELECT :NEW.subscriber_id AS sid FROM dual) s
  ON (u.subscriber_id = s.sid)
  WHEN MATCHED THEN UPDATE SET
    u.total_mb  = u.total_mb  + :NEW.mb,
    u.total_min = u.total_min + :NEW.minutes,
    u.cost      = u.cost      + :NEW.cost
  WHEN NOT MATCHED THEN INSERT (subscriber_id, total_mb, total_min, cost)
    VALUES (:NEW.subscriber_id, :NEW.mb, :NEW.minutes, :NEW.cost);
END;
/

INSERT INTO cp_subscribers
SELECT 'S-001', '+1-202-555-0111', 'UNLIMITED',
       JSON_OBJECT(
         'name' VALUE 'Avery Quinn', 'email' VALUE 'avery.quinn@example.net', 'since' VALUE '2019-04-12',
         'billingAddress' VALUE JSON_OBJECT('line1' VALUE '1450 Harbor Way', 'city' VALUE 'Alexandria', 'region' VALUE 'VA', 'postal' VALUE '22314'),
         'serviceAddress' VALUE JSON_OBJECT('line1' VALUE '1450 Harbor Way', 'city' VALUE 'Alexandria', 'region' VALUE 'VA', 'postal' VALUE '22314'),
         'devices' VALUE JSON_ARRAY(
           JSON_OBJECT('imei' VALUE '356938035643809', 'model' VALUE 'Pixel 9', 'sim' VALUE '8901410321111851072', 'activatedOn' VALUE '2024-10-03'),
           JSON_OBJECT('imei' VALUE '354812090211457', 'model' VALUE 'Galaxy Watch 7', 'sim' VALUE '8901410321111851099', 'activatedOn' VALUE '2025-02-18')),
         'addOns' VALUE JSON_ARRAY('INTL_ROAM', 'HOTSPOT_50GB', 'DEVICE_PROTECT'),
         'preferences' VALUE JSON_OBJECT('paperless' VALUE 'yes', 'language' VALUE 'en-US', 'alerts' VALUE JSON_ARRAY('usage-80', 'usage-100', 'bill-ready')),
         'consents' VALUE JSON_ARRAY('marketing-email:2024-01-05', 'cpni-share:none', 'analytics:2023-11-30'),
         'accountHistory' VALUE (
           SELECT JSON_ARRAYAGG(JSON_OBJECT(
                    'ts' VALUE TO_CHAR(DATE '2025-01-01' + k * 7, 'YYYY-MM-DD'),
                    'type' VALUE DECODE(MOD(k, 4), 0, 'payment', 1, 'plan-change', 2, 'support-case', 'device-update'),
                    'channel' VALUE DECODE(MOD(k, 3), 0, 'app', 1, 'store', 'call-center'),
                    'note' VALUE 'Entry ' || k || ': reviewed with the customer and recorded by the agent for the account file')
                  ORDER BY k RETURNING JSON)
           FROM (SELECT LEVEL AS k FROM dual CONNECT BY LEVEL <= 35))
         RETURNING JSON)
FROM   dual;
INSERT INTO cp_subscribers
SELECT 'S-002', '+1-202-555-0122', 'METERED',
       JSON_OBJECT(
         'name' VALUE 'Jordan Ellis', 'email' VALUE 'jordan.ellis@example.net', 'since' VALUE '2019-04-12',
         'billingAddress' VALUE JSON_OBJECT('line1' VALUE '1450 Harbor Way', 'city' VALUE 'Alexandria', 'region' VALUE 'VA', 'postal' VALUE '22314'),
         'serviceAddress' VALUE JSON_OBJECT('line1' VALUE '1450 Harbor Way', 'city' VALUE 'Alexandria', 'region' VALUE 'VA', 'postal' VALUE '22314'),
         'devices' VALUE JSON_ARRAY(
           JSON_OBJECT('imei' VALUE '356938035643809', 'model' VALUE 'Pixel 9', 'sim' VALUE '8901410321111851072', 'activatedOn' VALUE '2024-10-03'),
           JSON_OBJECT('imei' VALUE '354812090211457', 'model' VALUE 'Galaxy Watch 7', 'sim' VALUE '8901410321111851099', 'activatedOn' VALUE '2025-02-18')),
         'addOns' VALUE JSON_ARRAY('INTL_ROAM', 'HOTSPOT_50GB', 'DEVICE_PROTECT'),
         'preferences' VALUE JSON_OBJECT('paperless' VALUE 'yes', 'language' VALUE 'en-US', 'alerts' VALUE JSON_ARRAY('usage-80', 'usage-100', 'bill-ready')),
         'consents' VALUE JSON_ARRAY('marketing-email:2024-01-05', 'cpni-share:none', 'analytics:2023-11-30'),
         'accountHistory' VALUE (
           SELECT JSON_ARRAYAGG(JSON_OBJECT(
                    'ts' VALUE TO_CHAR(DATE '2025-01-01' + k * 7, 'YYYY-MM-DD'),
                    'type' VALUE DECODE(MOD(k, 4), 0, 'payment', 1, 'plan-change', 2, 'support-case', 'device-update'),
                    'channel' VALUE DECODE(MOD(k, 3), 0, 'app', 1, 'store', 'call-center'),
                    'note' VALUE 'Entry ' || k || ': reviewed with the customer and recorded by the agent for the account file')
                  ORDER BY k RETURNING JSON)
           FROM (SELECT LEVEL AS k FROM dual CONNECT BY LEVEL <= 6))
         RETURNING JSON)
FROM   dual;
INSERT INTO cp_subscribers
SELECT 'S-003', '+1-202-555-0133', 'UNLIMITED',
       JSON_OBJECT(
         'name' VALUE 'Riley Moreno', 'email' VALUE 'riley.moreno@example.net', 'since' VALUE '2019-04-12',
         'billingAddress' VALUE JSON_OBJECT('line1' VALUE '1450 Harbor Way', 'city' VALUE 'Alexandria', 'region' VALUE 'VA', 'postal' VALUE '22314'),
         'serviceAddress' VALUE JSON_OBJECT('line1' VALUE '1450 Harbor Way', 'city' VALUE 'Alexandria', 'region' VALUE 'VA', 'postal' VALUE '22314'),
         'devices' VALUE JSON_ARRAY(
           JSON_OBJECT('imei' VALUE '356938035643809', 'model' VALUE 'Pixel 9', 'sim' VALUE '8901410321111851072', 'activatedOn' VALUE '2024-10-03'),
           JSON_OBJECT('imei' VALUE '354812090211457', 'model' VALUE 'Galaxy Watch 7', 'sim' VALUE '8901410321111851099', 'activatedOn' VALUE '2025-02-18')),
         'addOns' VALUE JSON_ARRAY('INTL_ROAM', 'HOTSPOT_50GB', 'DEVICE_PROTECT'),
         'preferences' VALUE JSON_OBJECT('paperless' VALUE 'yes', 'language' VALUE 'en-US', 'alerts' VALUE JSON_ARRAY('usage-80', 'usage-100', 'bill-ready')),
         'consents' VALUE JSON_ARRAY('marketing-email:2024-01-05', 'cpni-share:none', 'analytics:2023-11-30'),
         'accountHistory' VALUE (
           SELECT JSON_ARRAYAGG(JSON_OBJECT(
                    'ts' VALUE TO_CHAR(DATE '2025-01-01' + k * 7, 'YYYY-MM-DD'),
                    'type' VALUE DECODE(MOD(k, 4), 0, 'payment', 1, 'plan-change', 2, 'support-case', 'device-update'),
                    'channel' VALUE DECODE(MOD(k, 3), 0, 'app', 1, 'store', 'call-center'),
                    'note' VALUE 'Entry ' || k || ': reviewed with the customer and recorded by the agent for the account file')
                  ORDER BY k RETURNING JSON)
           FROM (SELECT LEVEL AS k FROM dual CONNECT BY LEVEL <= 12))
         RETURNING JSON)
FROM   dual;

-- The same mid-cycle state as the document model: 1,000 prior CDRs for S-001
-- (the trigger builds the matching summary row), one each for S-002 and S-003.
INSERT INTO cp_cdr (subscriber_id, mb, minutes, cost, cdr_ts)
SELECT 'S-001',
       50 + MOD(LEVEL * 37, 200),
       1 + MOD(LEVEL * 13, 30),
       ROUND((1 + MOD(LEVEL * 13, 30)) * 0.03, 2),
       TIMESTAMP '2026-09-01 00:00:00' + NUMTODSINTERVAL(LEVEL * 40, 'MINUTE')
FROM   dual CONNECT BY LEVEL <= 1000;
INSERT INTO cp_cdr (subscriber_id, mb, minutes, cost, cdr_ts) VALUES ('S-002', 50, 5,0.15, TIMESTAMP '2026-09-02 09:00:00');
INSERT INTO cp_cdr (subscriber_id, mb, minutes, cost, cdr_ts) VALUES ('S-003',900,40,2.70, TIMESTAMP '2026-09-03 14:00:00');
COMMIT;

-- CDRs stream in as tiny appends; the summary tracks them in the same commit.
-- @step Record one CDR for S-001 (the trigger bumps the summary row)
-- @note One small row; the trigger bumps the narrow summary row in the same transaction. The subscriber's profile is not touched.
-- @why Update locality still lands on one subscriber, but the summary is a narrow row: three counters change and three counters are written, not the whole subscriber profile.
-- @look Rows affected is 1; Measure it shows redo near 1.8 KB however large the subscriber's profile is.
-- @figure erd.svg Subscriber, CDR and usage summary in canonical form, beside the subscriber document whose whole profile every summary update rewrites
-- @measure record-cdr
-- @mongo db.aggregate([{ $sql: `
-- @mongo   INSERT INTO cp_cdr (subscriber_id, mb, minutes, cost) VALUES ('S-001',120,12,0.36)
-- @mongo ` }])
INSERT INTO cp_cdr (subscriber_id, mb, minutes, cost) VALUES ('S-001',120,12,0.36);
COMMIT;

-- Account page read: the rollup is already there (staleness = 0), one PK lookup.
-- @step Read the account page (rollup already there)
-- @note Staleness = 0: the trigger kept this current in the same transaction as the CDR insert.
-- @why Read/write: the balance check still reads a precomputed rollup, now from a narrow summary row the trigger keeps current in the CDR's own transaction.
-- @look total_mb and cost come from one primary-key lookup on cp_subscriber_usage, with no aggregation over cp_cdr.
-- @mongo db.aggregate([{ $sql: `
-- @mongo   SELECT subscriber_id, total_mb, cost FROM cp_subscriber_usage WHERE subscriber_id = 'S-001'
-- @mongo ` }])
SELECT subscriber_id, total_mb, cost FROM cp_subscriber_usage WHERE subscriber_id = 'S-001';

-- Hot Top-N: an index range scan on cp_ix_usage_topn + FETCH FIRST N.
-- (EXPLAIN PLAN FOR this SELECT shows INDEX RANGE SCAN, not SORT ORDER BY.)
-- @step Rank the top talkers (index range scan)
-- @note No SUM, no SORT: the descending index turns Top-N into a range scan that stops after N rows.
-- @note Field result for this change (anonymized): the dashboard's hot Top-N went from 60 s to 500 ms.
-- @why Diversity: the ops dashboard gets its own access path, a descending index on total_mb, so Top-N stops after 5 index entries instead of sorting every subscriber.
-- @look Up to 5 rows in total_mb order, the same ranking as the document model's sort, read from the head of the index.
-- @mongo db.aggregate([{ $sql: `
-- @mongo   SELECT subscriber_id, total_mb, cost
-- @mongo   FROM   cp_subscriber_usage
-- @mongo   ORDER  BY total_mb DESC
-- @mongo   FETCH  FIRST 5 ROWS ONLY
-- @mongo ` }])
SELECT subscriber_id, total_mb, cost
FROM   cp_subscriber_usage
ORDER  BY total_mb DESC
FETCH  FIRST 5 ROWS ONLY;

-- Prefer the document shape at the API? Project it: rollup included, live.
CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW cp_subscriber_dv AS
SELECT JSON {
  '_id'    : s.subscriber_id,
  'msisdn' : s.msisdn WITH UPDATE,
  'plan'   : s.plan   WITH UPDATE,
  'profile': s.profile WITH UPDATE,
  'cycleUsage' : ( SELECT JSON { 'totalMB' : u.total_mb,
                                 'totalMin': u.total_min,
                                 'cost'    : u.cost }
                   FROM cp_subscriber_usage u WITH NOUPDATE
                   WHERE u.subscriber_id = s.subscriber_id )
} FROM cp_subscribers s WITH INSERT UPDATE DELETE;

-- @step Read the projected subscriber document
-- @note The duality view includes the live rollup: no separate document to maintain for the API shape.
-- @why Diversity without a second copy: the duality view projects the subscriber document with cycleUsage inline and read-only, joined by primary key on each read.
-- @look subscriber_document shows cycleUsage with the same totals as the account-page read.
-- @mongo db.cp_subscriber_dv.find({ _id: "S-001" })
SELECT JSON_SERIALIZE(data RETURNING CLOB PRETTY) AS subscriber_document
FROM   cp_subscriber_dv WHERE JSON_VALUE(data,'$._id') = 'S-001';
