-- ============================================================================
-- Pattern 03 · Bucket (time-series) · THE CONVERGED ALTERNATIVE
-- Stop hand-rolling buckets. Let range partitioning do the amortization the
-- bucket was faking, and let GROUP BY do the rollup.
--
-- Readings are tiny, append-only rows in an INTERVAL-partitioned table -- Oracle
-- opens a new hourly partition automatically as time advances. Each reading is a
-- single small row: no array to grow, no bucket document to rewrite, no 16 MB
-- ceiling. The per-hour summary is kept current INCREMENTALLY: an AFTER INSERT
-- trigger bumps one narrow row per machine-metric-hour (count, sum, max) in the
-- reading's own transaction, so the dashboard reads one row and the rollup is
-- never stale. GROUP BY over the partition range stays available for any
-- question the summary doesn't answer. Want it through the MongoDB API? A $sql stage
-- (Oracle's addition to the aggregation pipeline) runs the same GROUP BY with
-- parallel execution and NO 100 MB stage / 16 MB output caps (see README).
--
-- The needle-flip, resolved: each reading is a constant-cost single-row insert
-- instead of an ever-growing document rewrite, and there is no document ceiling
-- to march toward. The price: the last-hour dashboard scans rows instead of
-- fetching one document, about 2x the read bytes in the deck's model. An
-- anonymized field result for exactly this reshape: a 29s bucket rollup fell to
-- under 400ms, paid for with that heavier last-hour read. Slow sensors (below
-- ~900 readings a bucket) are still better served by the bucket.
-- Run:  sqlplus cmp_user/CmpUser2026@localhost:1521/FREEPDB1 @02-converged.sql
-- ============================================================================

BEGIN
  FOR r IN (SELECT mview_name FROM user_mviews WHERE mview_name = 'BK_HOURLY_MV') LOOP
    EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW ' || r.mview_name;
  END LOOP;
  FOR r IN (SELECT table_name FROM user_tables WHERE table_name IN ('BK_SENSOR_READINGS', 'BK_SENSOR_HOURLY')) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' PURGE';
  END LOOP;
END;
/

-- Append-only, INTERVAL-partitioned by the hour. New partitions appear on their
-- own as readings cross hour boundaries -- the amortization the bucket faked,
-- done by the engine.
CREATE TABLE bk_sensor_readings (
  reading_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
  machine_id  VARCHAR2(16)  NOT NULL,
  metric      VARCHAR2(24)  NOT NULL,
  reading_val NUMBER(12,3)  NOT NULL,
  reading_ts  TIMESTAMP     NOT NULL
)
PARTITION BY RANGE (reading_ts)
INTERVAL (INTERVAL '1' HOUR)
( PARTITION p_seed VALUES LESS THAN (TIMESTAMP '2026-08-01 00:00:00') );

CREATE INDEX bk_ix_readings ON bk_sensor_readings (machine_id, metric, reading_ts);

-- The running rollup: one narrow row per machine, metric and hour, maintained
-- incrementally as each reading lands. Rate no longer sizes anything: a reading
-- costs one small insert plus one counter bump at any cadence.
CREATE TABLE bk_sensor_hourly (
  machine_id VARCHAR2(16) NOT NULL,
  metric     VARCHAR2(24) NOT NULL,
  hour_start DATE         NOT NULL,
  n          NUMBER       NOT NULL,
  sum_val    NUMBER       NOT NULL,
  max_val    NUMBER       NOT NULL,
  CONSTRAINT bk_pk_hourly PRIMARY KEY (machine_id, metric, hour_start)
);

-- Measured on 26ai Free (per reading, one reading per commit): this trigger adds
-- ~375 B of redo and ~14 us to the insert. The declarative alternative, a
-- materialized view REFRESH FAST ON COMMIT over a view log, adds ~7.4 KB and
-- ~1.3 ms (the log alone costs more than this whole trigger; the commit-time
-- refresh is most of the rest). Both are exact; the trigger is the cheap one.
CREATE OR REPLACE TRIGGER bk_trg_hourly
AFTER INSERT ON bk_sensor_readings
FOR EACH ROW
BEGIN
  MERGE INTO bk_sensor_hourly h
  USING (SELECT :NEW.machine_id AS m, :NEW.metric AS k, CAST(TRUNC(:NEW.reading_ts, 'HH24') AS DATE) AS hs FROM dual) x
  ON (h.machine_id = x.m AND h.metric = x.k AND h.hour_start = x.hs)
  WHEN MATCHED THEN UPDATE SET h.n = h.n + 1, h.sum_val = h.sum_val + :NEW.reading_val,
                               h.max_val = GREATEST(h.max_val, :NEW.reading_val)
  WHEN NOT MATCHED THEN INSERT (machine_id, metric, hour_start, n, sum_val, max_val)
    VALUES (:NEW.machine_id, :NEW.metric, x.hs, 1, :NEW.reading_val, :NEW.reading_val);
END;
/

-- The hour's first 30 readings (the same 30 the bucket already holds). The trigger
-- creates the hour's summary row on the first of them, so the measured write below
-- is a steady-state reading: insert + bump an existing summary row.
INSERT INTO bk_sensor_readings (machine_id, metric, reading_val, reading_ts)
SELECT 'M-100', 'TEMP', 80 + MOD(LEVEL * 7, 150) / 10, TIMESTAMP '2026-08-01 10:01:00' + NUMTODSINTERVAL(LEVEL, 'SECOND')
FROM   dual CONNECT BY LEVEL <= 30;
COMMIT;

-- Every reading is one small row. No parent to rewrite; constant cost per reading.
-- The same three readings the document model appends to its bucket, as three rows.
-- @step Insert the three readings
-- @note Three small rows: no bucket to grow, no parent document to rewrite.
-- @why Update locality stops compounding: each reading is its own small row in the hour's partition, so an insert costs the same at reading 3 or reading 36,000. There is no document to grow and no 16 MB cap to reach.
-- @look Rows affected is 3; Measure it shows about 2.8 KB of redo for the three inserts and their summary bumps, flat at any bucket size.
-- @figure erd.svg Plant, machine and append-only readings with a derived hourly rollup, beside one hot sensor-hour packed into a single bucket
-- @mongo db.aggregate([{ $sql: `
-- @mongo   INSERT INTO bk_sensor_readings (machine_id, metric, reading_val, reading_ts)
-- @mongo   SELECT 'M-100', 'TEMP', 88.4, TIMESTAMP '2026-08-01 10:00:05' FROM dual UNION ALL
-- @mongo   SELECT 'M-100', 'TEMP', 89.1, TIMESTAMP '2026-08-01 10:00:10' FROM dual UNION ALL
-- @mongo   SELECT 'M-100', 'TEMP', 91.7, TIMESTAMP '2026-08-01 10:00:15' FROM dual
-- @mongo ` }])
-- @measure ingest-reading
INSERT INTO bk_sensor_readings (machine_id, metric, reading_val, reading_ts)
SELECT 'M-100', 'TEMP', 88.4, TIMESTAMP '2026-08-01 10:00:05' FROM dual UNION ALL
SELECT 'M-100', 'TEMP', 89.1, TIMESTAMP '2026-08-01 10:00:10' FROM dual UNION ALL
SELECT 'M-100', 'TEMP', 91.7, TIMESTAMP '2026-08-01 10:00:15' FROM dual;
INSERT INTO bk_sensor_readings (machine_id, metric, reading_val, reading_ts) VALUES ('M-100','TEMP',80.2, TIMESTAMP '2026-08-01 11:03:00');
INSERT INTO bk_sensor_readings (machine_id, metric, reading_val, reading_ts) VALUES ('M-200','TEMP',60.0, TIMESTAMP '2026-08-01 10:30:00');
COMMIT;

-- The rollup = GROUP BY over a partitioned range. Same answer the bucket
-- counters gave, computed on read, nothing maintained on write. Asking for a
-- single hour prunes to a single partition.
-- @step Roll up the hour with GROUP BY
-- @note Same answer the bucket counters gave, computed on read instead of maintained on every write.
-- @note The readings are relational rows; through the MongoDB API they are reached with $sql, the same SQL running as one stage of a MongoDB aggregation.
-- @why Read/write, priced honestly: the rollup is computed on read and pruned to the partitions asked for, but a range scan pays per row where the bucket was one fetch. Where reads repeat, the materialized view precomputes it.
-- @look One row per machine and hour with n, avg_val and max_val, computed from the rows rather than maintained on every write.
-- @mongo db.aggregate([{ $sql: `
-- @mongo   SELECT machine_id, metric, TRUNC(reading_ts, 'HH24') AS hour_start,
-- @mongo          COUNT(*)                   AS n,
-- @mongo          ROUND(AVG(reading_val), 3) AS avg_val,
-- @mongo          MAX(reading_val)           AS max_val
-- @mongo   FROM   bk_sensor_readings
-- @mongo   GROUP  BY machine_id, metric, TRUNC(reading_ts, 'HH24')
-- @mongo   ORDER  BY machine_id, metric, hour_start
-- @mongo ` }])
SELECT machine_id, metric, TRUNC(reading_ts, 'HH24') AS hour_start,
       COUNT(*)                   AS n,
       ROUND(AVG(reading_val), 3) AS avg_val,
       MAX(reading_val)           AS max_val
FROM   bk_sensor_readings
GROUP  BY machine_id, metric, TRUNC(reading_ts, 'HH24')
ORDER  BY machine_id, metric, hour_start;

-- The dashboard read: one row per machine-metric-hour, already summed by the
-- trigger, staleness zero. This is the read the bucket was built to serve.
-- @step Read the hour from the summary row
-- @measure-read read
-- @note One primary-key row per machine and hour: no scan, no bucket, current as of the last commit.
-- @why Read/write without the bucket's bet: the trigger did the rollup incrementally as each reading landed, so the 360-a-day dashboard reads one narrow row however fast the sensor reports.
-- @look n, avg_val and max_val match the GROUP BY card exactly, read from one row per machine and hour.
-- @mongo db.aggregate([{ $sql: `
-- @mongo   SELECT machine_id, metric, hour_start, n,
-- @mongo          ROUND(sum_val / n, 3) AS avg_val, max_val
-- @mongo   FROM   bk_sensor_hourly
-- @mongo   ORDER  BY machine_id, metric, hour_start
-- @mongo ` }])
SELECT machine_id, metric, hour_start, n,
       ROUND(sum_val / n, 3) AS avg_val, max_val
FROM   bk_sensor_hourly
ORDER  BY machine_id, metric, hour_start;
