-- ============================================================================
-- Pattern 03 · Bucket (time-series) · THE CONVERGED ALTERNATIVE
-- Stop hand-rolling buckets. Let range partitioning do the amortization the
-- bucket was faking, and let GROUP BY do the rollup.
--
-- Readings are tiny, append-only rows in an INTERVAL-partitioned table -- Oracle
-- opens a new hourly partition automatically as time advances. Each insert is a
-- single small row: no array to grow, no bucket document to rewrite, no 16 MB
-- ceiling. The per-hour summary is a GROUP BY over a partition range (the
-- optimizer prunes to just the hours asked for). Want it precomputed? A
-- materialized view rolls it up; want it through the Mongo lane? $sql-in-pipeline
-- runs the same GROUP BY with parallel execution and NO 100 MB stage / 16 MB
-- output caps (see README). Field result for exactly this reshape: a 29s bucket
-- rollup fell to sub-400ms, and the read win was kept without maintaining a bucket.
--
-- The needle-flip, resolved: the write is a constant-cost single-row insert
-- instead of an ever-growing document rewrite, and there is no document ceiling
-- to march toward.
-- Run:  sqlplus cmp_user/CmpUser2026@localhost:1521/FREEPDB1 @02-converged.sql
-- ============================================================================

BEGIN
  FOR r IN (SELECT table_name FROM user_tables WHERE table_name = 'BK_SENSOR_READINGS') LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' PURGE';
  END LOOP;
END;
/

-- Append-only, INTERVAL-partitioned by the hour. New partitions appear on their
-- own as readings cross hour boundaries -- the amortization the bucket faked,
-- done by the engine.
CREATE TABLE bk_sensor_readings (
  reading_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
  machine_id  VARCHAR2(16)  NOT NULL,
  metric      VARCHAR2(24)  NOT NULL,
  reading_val NUMBER(12,3)  NOT NULL,
  reading_ts  TIMESTAMP     NOT NULL
)
PARTITION BY RANGE (reading_ts)
INTERVAL (INTERVAL '1' HOUR)
( PARTITION p_seed VALUES LESS THAN (TIMESTAMP '2026-08-01 00:00:00') );

CREATE INDEX bk_ix_readings ON bk_sensor_readings (machine_id, metric, reading_ts);

-- Every reading is one small insert. No parent to rewrite; constant cost.
-- @step Insert one reading
-- @note A single small row — no bucket to grow, no parent document to rewrite.
-- @measure ingest-reading
INSERT INTO bk_sensor_readings (machine_id, metric, reading_val, reading_ts) VALUES ('M-100','TEMP',88.4, TIMESTAMP '2026-08-01 10:00:05');
INSERT INTO bk_sensor_readings (machine_id, metric, reading_val, reading_ts) VALUES ('M-100','TEMP',89.1, TIMESTAMP '2026-08-01 10:00:10');
INSERT INTO bk_sensor_readings (machine_id, metric, reading_val, reading_ts) VALUES ('M-100','TEMP',91.7, TIMESTAMP '2026-08-01 10:00:15');
INSERT INTO bk_sensor_readings (machine_id, metric, reading_val, reading_ts) VALUES ('M-100','TEMP',80.2, TIMESTAMP '2026-08-01 11:03:00');
INSERT INTO bk_sensor_readings (machine_id, metric, reading_val, reading_ts) VALUES ('M-200','TEMP',60.0, TIMESTAMP '2026-08-01 10:30:00');
COMMIT;

-- The rollup = GROUP BY over a partitioned range. Same answer the bucket
-- counters gave, computed on read, nothing maintained on write. Asking for a
-- single hour prunes to a single partition.
-- @step Roll up the hour with GROUP BY
-- @note Same answer the bucket counters gave, computed on read instead of maintained on every write.
SELECT machine_id, metric, TRUNC(reading_ts, 'HH24') AS hour_start,
       COUNT(*)                   AS n,
       ROUND(AVG(reading_val), 3) AS avg_val,
       MAX(reading_val)           AS max_val
FROM   bk_sensor_readings
GROUP  BY machine_id, metric, TRUNC(reading_ts, 'HH24')
ORDER  BY machine_id, metric, hour_start;

-- Precompute it if reads dwarf writes: a summary MV over the same rows. (Add
-- REFRESH FAST ON COMMIT + a materialized view log to make it staleness = 0.)
BEGIN
  FOR r IN (SELECT mview_name FROM user_mviews WHERE mview_name = 'BK_HOURLY_MV') LOOP
    EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW ' || r.mview_name;
  END LOOP;
END;
/
CREATE MATERIALIZED VIEW bk_hourly_mv
BUILD IMMEDIATE REFRESH COMPLETE ON DEMAND AS
SELECT machine_id, metric, TRUNC(reading_ts, 'HH24') AS hour_start,
       COUNT(*) AS n, SUM(reading_val) AS sum_val, MAX(reading_val) AS max_val
FROM   bk_sensor_readings
GROUP  BY machine_id, metric, TRUNC(reading_ts, 'HH24');

SELECT machine_id, metric, hour_start, n,
       ROUND(sum_val/n, 3) AS avg_val, max_val
FROM   bk_hourly_mv
ORDER  BY machine_id, metric, hour_start;
