-- Grant CMP_USER (created by the gvenzl APP_USER convention) the privileges the
-- patterns use. Runs as SYSDBA at initdb time (gvenzl convention). Idempotent.
ALTER SESSION SET CONTAINER = FREEPDB1;
BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'CREATE USER cmp_user IDENTIFIED BY "CmpUser2026" QUOTA UNLIMITED ON users';
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -1920 THEN RAISE; END IF;  -- ORA-01920: user already exists (created by image)
  END;
  EXECUTE IMMEDIATE 'ALTER USER cmp_user QUOTA UNLIMITED ON users';
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE,
    CREATE TRIGGER, CREATE SEQUENCE, CREATE MATERIALIZED VIEW, CREATE PROPERTY GRAPH,
    SODA_APP TO cmp_user';
END;
/
