// Generates docs/help-review.md: every help entry by pattern, surface and statement, so the
// author can review all lab guidance text in one place. Flags cards that have no help.
import fs from 'node:fs';
import path from 'node:path';
import { loadPatterns } from '../src/content/patterns.js';

const root = path.resolve(import.meta.dirname, '../../patterns');
const out = [];
const line = (s = '') => out.push(s);
const help = (hp) => [hp?.why && `- **Why:** ${hp.why}`, hp?.look && `- **Look for:** ${hp.look}`, hp?.figure && `- **Figure:** \`${hp.figure.file}\`: ${hp.figure.caption ?? ''}`].filter(Boolean);
let missing = 0;
line('# Lab help text: review'); line(); line('Generated by `app/scripts/help-review.mjs`. Edit the pattern files, not this file.'); line();
for (const p of loadPatterns(root)) {
  line(`## ${p.id} · ${p.meta.title}`); line();
  line('### Knobs'); for (const k of p.meta.knobs) line(`- **${k.name}** (${k.setting}): ${k.help ?? '⚠ MISSING'}`); line();
  // The MongoDB API tab only renders when the pattern has mongosh cards, so only then does it need help.
  const tabKeys = ['document', 'converged', ...(p.lanes.mongo.length ? ['mongo'] : []), 'measure'];
  line('### Tabs'); for (const k of tabKeys) { const t = p.meta.help.tabs[k]; line(`**${k}**`); const hl = help(t); if (!hl.length) { line('- ⚠ MISSING'); missing++; } else hl.forEach(line); line(); }
  for (const [lane, steps] of Object.entries(p.lanes)) {
    if (!steps.length) continue;
    line(`### ${lane} cards`); line();
    for (const st of steps) {
      line(`**${st.title}**${st.measure ? ` · measured: ${st.measure}` : ''}`);
      const hl = help(st.help); if (!hl.length) { line('- ⚠ MISSING'); missing++; } else hl.forEach(line);
      line();
    }
  }
}
out.splice(3, 0, `Entries missing help: **${missing}**`, '');
fs.writeFileSync(path.resolve(import.meta.dirname, '../../docs/help-review.md'), out.join('\n'));
console.log(`docs/help-review.md written · ${missing} missing`);
